const fs = require("fs");
const lines = [];
lines.push("\"use client\";");
lines.push("");
lines.push("import Link from \"next/link\";");
lines.push("import { usePathname } from \"next/navigation\";");
lines.push("import {");
lines.push("  LayoutDashboard,");
lines.push("  Users,");
lines.push("  Building2,");
lines.push("  FolderKanban,");
lines.push("  CreditCard,");
lines.push("  BarChart3,");
lines.push("  Shield,");
lines.push("  FileText,");
lines.push("  UserPlus,");
lines.push("  BadgeCheck,");
lines.push("  Activity,");
lines.push("  Award,");
lines.push("  LogOut,");
lines.push("  Menu,");
lines.push("  X,");
lines.push("  Megaphone,");
lines.push("  Settings,");
lines.push("  AlertTriangle,");
lines.push("} from \"lucide-react\";");
lines.push("import { cn } from \"@/components/ui/utils\";");
lines.push("import { Button } from \"@/components/ui/button\";");
lines.push("import { useUIStore } from \"@/store/ui.store\";");
lines.push("import { useAuthStore } from \"@/store/auth.store\";");
lines.push("");
lines.push("const navItems = [");
lines.push("  {");
lines.push("    title: \"Overview\",");
lines.push("    href: \"/dashboard\",");
lines.push("    icon: LayoutDashboard,");
lines.push("  },");
lines.push("  {");
lines.push("    title: \"Users\",");
lines.push("    href: \"/dashboard/users\",");
lines.push("    icon: Users,");
lines.push("  },");
lines.push("  {");
lines.push("    title: \"Agencies\",");
lines.push("    href: \"/dashboard/agencies\",");
lines.push("    icon: Building2,");
lines.push("  },");
lines.push("  {");
lines.push("    title: \"Campaigns\",");
lines.push("    href: \"/dashboard/campaigns\",");
lines.push("    icon: FolderKanban,");
lines.push("  },");
lines.push("  {");
lines.push("    title: \"Payments\",");
lines.push("    href: \"/dashboard/payments\",");
lines.push("    icon: CreditCard,");
lines.push("  },");
lines.push("  {");
lines.push("    title: \"Analytics\",");
lines.push("    href: \"/dashboard/analytics\",");
lines.push("    icon: BarChart3,");
lines.push("  },");
lines.push("  {");
lines.push("    title: \"Moderation\",");
lines.push("    href: \"/dashboard/moderation\",");
lines.push("    icon: Shield,");
lines.push("  },");
lines.push("  {");
lines.push("    title: \"Fraud Monitoring\",");
lines.push("    href: \"/dashboard/fraud\",");
lines.push("    icon: AlertTriangle,");
lines.push("  },");
lines.push("  {");
lines.push("    title: \"Audit Log\",");
lines.push("    href: \"/dashboard/audit-log\",");
lines.push("    icon: FileText,");
lines.push("  },");
lines.push("  {");
lines.push("    title: \"Invites\",");
lines.push("    href: \"/dashboard/invites\",");
lines.push("    icon: UserPlus,");
lines.push("  },");
lines.push("  {");
lines.push("    title: \"KYC\",");
lines.push("    href: \"/dashboard/kyc\",");
lines.push("    icon: BadgeCheck,");
lines.push("  },");
lines.push("  {");
lines.push("    title: \"Badges\",");
lines.push("    href: \"/dashboard/badges\",");
lines.push("    icon: Activity,");
lines.push("  },");
lines.push("  {");
lines.push("    title: \"Broadcast\",");
lines.push("    href: \"/dashboard/broadcast\",");
lines.push("    icon: Megaphone,");
lines.push("  },");
lines.push("  {");
lines.push("    title: \"Settings\",");
lines.push("    href: \"/dashboard/settings\",");
lines.push("    icon: Settings,");
lines.push("  },");
lines.push("  {");
lines.push("    title: \"Top Performers\",");
lines.push("    href: \"/dashboard/top-performers\",");
lines.push("    icon: Award,");
lines.push("  },");
lines.push("];");
lines.push("");
lines.push("export function Sidebar() {");
lines.push("  const pathname = usePathname();");
lines.push("  const { sidebarOpen, setSidebarOpen } = useUIStore();");
lines.push("  const { clearAuth } = useAuthStore();");
lines.push("");
lines.push("  const handleLogout = () => {");
lines.push("    clearAuth();");
lines.push("  };");
lines.push("");
lines.push("  return (");
lines.push("    <>");
lines.push("      {/* Mobile overlay */}");
lines.push("      {sidebarOpen && (");
lines.push("        <div");
lines.push("          className=\"fixed inset-0 z-40 bg-black/50 lg:hidden\"");
lines.push("          onClick={() => setSidebarOpen(false)}");
lines.push("        />");
lines.push("      )}");
lines.push("");
lines.push("      <aside");
lines.push("        className={cn(");
lines.push("          \"fixed left-0 top-0 z-50 flex h-screen w-64 flex-col border-r bg-background transition-transform duration-300 lg:translate-x-0\",");
lines.push("          sidebarOpen ? \"translate-x-0\" : \"-translate-x-full\",");
lines.push("        )}");
lines.push("      >");
lines.push("        <div className=\"flex h-16 items-center justify-between border-b px-6\">");
lines.push("          <div className=\"flex items-center gap-2\">");
lines.push("            <div className=\"flex size-8 items-center justify-center rounded-lg bg-gradient-to-r from-vaykae-pink to-vaykae-purple text-white\">");
lines.push("              <span className=\"text-sm font-bold\">V</span>");
lines.push("            </div>");
lines.push("            <span className=\"text-lg font-semibold\">Veakay</span>");
lines.push("          </div>");
lines.push("          <Button");
lines.push("            variant=\"ghost\"");
lines.push("            size=\"icon\"");
lines.push("            className=\"lg:hidden\"");
lines.push("            onClick={() => setSidebarOpen(false)}");
lines.push("          >");
lines.push("            <X className=\"size-5\" />");
lines.push("          </Button>");
lines.push("        </div>");
lines.push("");
lines.push("        <nav className=\"flex-1 space-y-1 overflow-y-auto p-4\">");
lines.push("          {navItems.map((item) => {");
lines.push("            const Icon = item.icon;");
lines.push("            const isActive =");
lines.push("              pathname === item.href ||");
lines.push("              pathname?.startsWith(item.href + \"/\");");
lines.push("            return (");
lines.push("              <Link");
lines.push("                key={item.href}");
lines.push("                href={item.href}");
lines.push("                onClick={() => setSidebarOpen(false)}");
lines.push("                className={cn(");
lines.push("                  \"flex items-center gap-3 rounded-lg px-3 py-2 text-sm font-medium transition-colors\",");
lines.push("                  isActive");
lines.push("                    ? \"bg-gradient-to-r from-vaykae-pink/10 to-vaykae-purple/10 text-vaykae-purple\"");
lines.push("                    : \"text-muted-foreground hover:bg-accent hover:text-foreground\",");
lines.push("                )}");
lines.push("              >");
lines.push("                <Icon className=\"size-5\" />");
lines.push("                {item.title}");
lines.push("              </Link>");
lines.push("            );");
lines.push("          })}");
lines.push("        </nav>");
lines.push("");
lines.push("        <div className=\"border-t p-4\">");
lines.push("          <Button");
lines.push("            variant=\"ghost\"");
lines.push("            className=\"w-full justify-start gap-3 text-muted-foreground\"");
lines.push("            onClick={handleLogout}");
lines.push("          >");
lines.push("            <LogOut className=\"size-5\" />");
lines.push("            Logout");
lines.push("          </Button>");
lines.push("        </div>");
lines.push("      </aside>");
lines.push("    </>");
lines.push("  );");
lines.push("}");
lines.push("");
lines.push("export function MobileMenuButton() {");
lines.push("  const { sidebarOpen, toggleSidebar } = useUIStore();");
lines.push("  return (");
lines.push("    <Button");
lines.push("      variant=\"ghost\"");
lines.push("      size=\"icon\"");
lines.push("      className=\"lg:hidden\"");
lines.push("      onClick={toggleSidebar}");
lines.push("    >");
lines.push("      {sidebarOpen ? (");
lines.push("        <X className=\"size-5\" />");
lines.push("      ) : (");
lines.push("        <Menu className=\"size-5\" />");
lines.push("      )}");
lines.push("    </Button>");
lines.push("  );");
lines.push("}");
const content = lines.join("\n");
fs.writeFileSync("C:/Users/LENOVO/Desktop/veakay-handoff/dashboard-repo/src/components/layout/sidebar.tsx", content, "utf8");
console.log("Done");
