export const ROUTES = {
  LOGIN: "/login",
  TWO_FACTOR: "/2fa",
  FORGOT_PASSWORD: "/forgot-password",
  ROOT: "/",
  DASHBOARD: "/dashboard",
  USERS: "/users",
  AGENCIES: "/agencies",
  CAMPAIGNS: "/campaigns",
  PAYMENTS: "/payments",
  CONTENT: "/content",
  NOTIFICATIONS: "/notifications",
  AUDIT: "/audit",
  SETTINGS: "/settings",
} as const;export const APP_TITLE = "Veakay";
